### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by mbndr** [fatrbaby/go-blade#1]
Hello, I'm a former PHP and Laravel developer, really like the Blade engine and would like to use it in Golang as well.

Can you give a quick statement how stable and usable this repository is? Except the generated godoc files I cannot find much information.

**Comment by fatrbaby** [comment]
@mbndr Hello, i am sorry for this project is not yet available. When I was coding, I realized that my implementation was not enough GOful. So I was thinking about redesigning my implementation, but it was shelved because I was busy recently. I will come up with a usable project and write doc as soon as possible. thx 4 attention.

**Comment by mbndr** [comment]
Ok thanks :)
Maybe I'll try implementing it on myself for learning purpose but I'll watch your repo for future implementations.
